# This Dockerfile is based upon: https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubi7/10.0/base/Dockerfile
FROM registry.redhat.io/ubi7/s2i-core
MAINTAINER "Courtney Pacheco <cpacheco@redhat.com>"

# Set NVIDIA environment vars
ENV CUDA_PACKAGE_VERSION=10-0
ENV CUDA_TOOLKIT_PATH=/usr/local/cuda

#<!-- taken from NVIDIA's Dockerfile -->
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411"
#<!-- end -->

# Set PATH vars
#<!-- taken from NVIDIA's Dockerfile -->
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
#<!-- end -->

# Copy user's 'rhel7-Latest.repo'
COPY repos/rhel7-Latest.repo /etc/yum.repos.d/rhel7-Latest.repo

# Copy user's 'rhel7-Server-Optional.repo'
COPY repos/rhel7-Server-Optional.repo /etc/yum.repos.d/rhel7-Server-Optional.repo

# Copy 'cuda repo'
COPY repos/rhel7-cuda.repo /etc/yum.repos.d/cuda.repo

# Install CUDA packages
RUN yum clean all && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum -y install cuda-${CUDA_PACKAGE_VERSION} \
                   cuda-cudart-${CUDA_PACKAGE_VERSION} \
                   cuda-core-${CUDA_PACKAGE_VERSION} \
                   cuda-cudart-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cufft-${CUDA_PACKAGE_VERSION} \
                   cuda-cufft-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cupti-${CUDA_PACKAGE_VERSION} \
                   cuda-curand-${CUDA_PACKAGE_VERSION} \
                   cuda-curand-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cusolver-${CUDA_PACKAGE_VERSION} \
                   cuda-cusolver-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cusparse-${CUDA_PACKAGE_VERSION} \
                   cuda-cusparse-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-misc-headers-${CUDA_PACKAGE_VERSION} \
                   libcublas-devel && \
    rm -rf /var/cache/yum/*

# Disable CUDA and RHEL 7 repos (for now). User can re-enable them later if desired.
RUN yum-config-manager --disablerepo rhel7-Latest && \
    yum-config-manager --disablerepo rhel7-Server-Optional && \
    yum-config-manager --disablerepo cuda

# Create 3rd party packages directory
ENV THIRD_PARTY_PKGS_DIR=${HOME}/3rd_party_pkgs
RUN mkdir -p ${THIRD_PARTY_PKGS_DIR}/cudnn && \
    mkdir -p ${THIRD_PARTY_PKGS_DIR}/nccl

# Pull in cuDNN
COPY gpu_packages/cudnn-cuda-10.0.tgz ${THIRD_PARTY_PKGS_DIR}/cudnn/cudnn.tgz
RUN cd ${THIRD_PARTY_PKGS_DIR}/cudnn && \
    tar xvf cudnn.tgz --strip-components=1 && \
    cp include/cudnn.h ${CUDA_TOOLKIT_PATH}/include/cudnn.h && \
    cp lib64/* ${CUDA_TOOLKIT_PATH}/lib64 && \
    rm -rf cudnn.tgz

# Pull in NCCL
COPY gpu_packages/nccl-cuda-10.0.txz ${THIRD_PARTY_PKGS_DIR}/nccl/nccl.txz
RUN cd ${THIRD_PARTY_PKGS_DIR}/nccl && \
    tar xJf nccl.txz --strip-components=1 && \
    rm -rf nccl.txz
