---

# Install packages on RHEL 7
- name: Install RHEL 7 optional CUDA packages
  yum:
    name:
      - cuda-core-{{ cuda_version }}
      - cuda-cudart-dev-{{ cuda_version }}
      - cuda-cufft-{{ cuda_version }}
      - cuda-cufft-dev-{{ cuda_version }}
      - cuda-cupti-{{ cuda_version }}
      - cuda-curand-{{ cuda_version }}
      - cuda-curand-dev-{{ cuda_version }}
      - cuda-cusolver-{{ cuda_version }}
      - cuda-cusolver-dev-{{ cuda_version }}
      - cuda-cusparse-{{ cuda_version }}
      - cuda-cusparse-dev-{{ cuda_version }}
      - cuda-misc-headers-{{ cuda_version }}
      - libcublas-devel
  when: rhel_version == '7'

# Install packages on RHEL 8
- name: Install RHEL 8 optional CUDA packages
  dnf:
    name:
      - cuda-core-{{ cuda_version }}
      - cuda-cudart-dev-{{ cuda_version }}
      - cuda-cufft-{{ cuda_version }}
      - cuda-cufft-dev-{{ cuda_version }}
      - cuda-cupti-{{ cuda_version }}
      - cuda-curand-{{ cuda_version }}
      - cuda-curand-dev-{{ cuda_version }}
      - cuda-cusolver-{{ cuda_version }}
      - cuda-cusolver-dev-{{ cuda_version }}
      - cuda-cusparse-{{ cuda_version }}
      - cuda-cusparse-dev-{{ cuda_version }}
      - cuda-misc-headers-{{ cuda_version }}
      - libcublas-devel
  when: rhel_version == '8'

# If we want to install cuda-toolkit, we need to install its dependencies first
- include_role:
    name: install_cuda_toolkit_deps
  when: install_cuda_toolkit == 'yes'

# Now install cuda toolkit
- name: Install CUDA toolkit on RHEL 7
  yum:
    name: cuda-toolkit-{{ cuda_version }}
  when: rhel_version == '7' and install_cuda_toolkit == 'yes'

- name: Install CUDA toolkit on RHEL 8
  dnf:
    name: cuda-toolkit-{{ cuda_version }}
  when: rhel_version == '8' and install_cuda_toolkit == 'yes'
