---

# The following commands are for RHEL 7 only, since FFTW in RHEL 7 is fftw-2.x.y and FFTW in RHEL 8 is fftw-3.x.y

################################################
#                    RHEL 7                    #
################################################
- block:
  - name: If using RHEL 7 and non-s2i/non-ubi, get FFTW2 source rpm
    shell: |
      cd {{ build_dir }}
      yumdownloader --source fftw2

  - name: Unpack source rpm and place the spec file in {{ build_dir }}
    shell: |
      cd {{ build_dir }}
      rpm2cpio fftw*.rpm | cpio -civ '*.spec'

  - find:
      paths: '{{ build_dir }}'
      patterns: '*.rpm'
    register: find_output

  - name: Remove source rpm since we don't need it anymore
    file:
      state: absent
      path: '{{ item["path"] }}'
    with_items: '{{ find_output["files"] }}'

  - name: If using RHEL 7, get FFTW2 version specified in the spec file
    shell: cd {{ build_dir }} && cat fftw2.spec | grep "Version:" | rev | cut -d " " -f 1 | rev
    register: fftw2_version

  - name: For RHEL 7 only -- FFTW2 version
    debug:
      var: fftw2_version.stdout

  # There is an FFTW tar file that comes with the source rpm, but we want the original source
  - name: For RHEL 7, get FFTW2 from fftw.org
    unarchive:
      src: 'http://fftw.org/fftw-{{ fftw2_version.stdout }}.tar.gz'
      dest: '{{ build_dir }}'
      remote_src: yes

  - name: If using RHEL 7, Remove FFTW2 spec file
    file:
      state: absent
      path: '{{ build_dir }}/fftw2.spec'

  - name: Rename fftw-2.x.y to FFTW
    command: mv {{ build_dir }}/fftw-{{ fftw2_version.stdout }} {{ build_dir }}/FFTW

  when: rhel_ver == "7" and ubi == "no" and s2i == "no"

################################################
#                 RHEL 8 / ubi7                #
################################################
- block:

  # Grab FFTW3 sources
  - name: For RHEL 8 and ubi7 builds, get FFTW3 from fftw.org
    unarchive:
      src: 'http://fftw.org/fftw-{{ fftw3_version }}.tar.gz'
      dest: '{{ build_dir }}'
      remote_src: yes

  - name: Rename fftw-{{ fftw3_ver }} to FFTW
    command: mv {{ build_dir }}/fftw-{{ fftw3_ver }} {{ build_dir }}/FFTW

  when: rhel_ver == "8" or (rhel_ver == "7" and s2i == "yes") or (rhel_ver == "7" and ubi == "yes")
