---

- name: Delete NCCL tmp dir (if it exists)
  file:
    state: absent
    path: /tmp/nccl

- name: Create NCCL tmp dir
  file:
    state: directory
    path: /tmp/nccl

- name: Download NCCL OS agnostic installer
  unarchive:
    src: '{{ NCCL_AGNOSTIC_LOCAL_INSTALLER }}'
    remote_src: yes
    dest: /tmp/nccl
    extra_opts: [--strip-components=1]

- debug:
    var: NCCL_INSTALL_PATH

- name: Remove {{ NCCL_INSTALL_PATH }} if it exists
  file:
    state: absent
    path: '{{ NCCL_INSTALL_PATH }}'

- name: Create {{ NCCL_INSTALL_PATH }}
  file:
    state: directory
    path: '{{ NCCL_INSTALL_PATH }}'

- name: Move /tmp/nccl contents to {{ NCCL_INSTALL_PATH }}
  command: mv '/tmp/nccl' '{{ NCCL_INSTALL_PATH }}'
