---

- name: Remove existing numpy site config file
  file:
    state: absent
    path: '{{ NUMPY_SITE_CFG }}'

- name: Set NumPy site config file for RHEL 7 -- use FFTW if specified
  shell: |
    echo '[ALL]' >> {{ NUMPY_SITE_CFG }}
    echo 'libraries = {{ FFTW_RHEL7_LIB_NAMES }}' >> {{ NUMPY_SITE_CFG }}
    echo 'library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'include_dirs = {{ BLAS_INCLUDE_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'runtime_library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'fftw_opt_libs = {{ FFTW_RHEL7_OPT_LIB_NAMES }}' >> {{ NUMPY_SITE_CFG }}
    echo '' >> {{ NUMPY_SITE_CFG }}
    echo '[atlas]' >> {{ NUMPY_SITE_CFG }}
    echo 'atlas_libs = lapack, blas, cblas, tatlas' >> {{ NUMPY_SITE_CFG }}
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no' and RHEL_VERSION == '7'

- name: Set NumPy site config file for RHEL 8 -- use FFTW if specified
  shell: |
    echo '[ALL]' >> {{ NUMPY_SITE_CFG }}
    echo 'libraries = {{ FFTW_RHEL8_LIB_NAMES }}' >> {{ NUMPY_SITE_CFG }}
    echo 'library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'include_dirs = {{ BLAS_INCLUDE_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'runtime_library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'fftw_opt_libs = {{ FFTW_RHEL8_OPT_LIB_NAMES }}' >> {{ NUMPY_SITE_CFG }}
    echo '' >> {{ NUMPY_SITE_CFG }}
    echo '[atlas]' >> {{ NUMPY_SITE_CFG }}
    echo 'atlas_libs = lapack, blas, cblas, tatlas' >> {{ NUMPY_SITE_CFG }}
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no' and RHEL_VERSION == '8'

- name: Some versions of NumPy do not work well with later versions of Cython, so we need to add the -3 flag
  lineinfile:
    path: '{{ NUMPY_BUILD_DIR }}/tools/cythonize.py'
    regexp: '.*flags\ ='
    line: "    flags = ['--fast-fail', '-3']"

- name: Configure and build NumPy -- use FFTW if specified
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    CC="{{ CC }} -lblas -lgfortran" python3 setup.py build_ext --build-lib fftw --fcompiler=gnu95
  environment:
    LD_LIBRARY_PATH: '/usr/lib:/usr/lib64:/usr/lib64/atlas:/usr/local/lib:{{ GCC_LIBS }}'
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no'
  register: numpy_fftw_log

- local_action: template src=fftw_numpy_log.j2 dest={{ NUMPY_BUILD_DIR }}/build.log
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no'

- name: Set NumPy site config file -- use OpenBLAS if specified
  shell: |
    echo '[ALL]' >> {{ NUMPY_SITE_CFG }}
    echo 'libraries = {{ OPENBLAS_LIB_NAMES }}' >> {{ NUMPY_SITE_CFG }}
    echo 'library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'include_dirs = {{ BLAS_INCLUDE_DIRS }}' >> {{ NUMPY_SITE_CFG }}
    echo 'runtime_library_dirs = {{ BLAS_LIB_DIRS }}' >> {{ NUMPY_SITE_CFG }}
  when: USE_FFTW == 'no' and USE_OPENBLAS == 'yes'

- name: Configure and build NumPy -- use OpenBLAS if specified
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    CC="gcc -lblas -lgfortran" python3 setup.py build_ext --build-lib fftw --fcompiler=gnu95
  environment:
    LD_LIBRARY_PATH: '/usr/lib:/usr/lib64:/usr/lib64/atlas:{{ GCC_LIBS }}'
  when: USE_FFTW == 'no' and USE_OPENBLAS == 'yes'
  register: numpy_openblas_log

- local_action: template src=openblas_numpy_log.j2 dest={{ NUMPY_BUILD_DIR }}/build.log
  when: USE_FFTW == 'no' and USE_OPENBLAS == 'yes'

- debug:
    msg: "NumPy build logs saved to {{ NUMPY_BUILD_DIR }}/build.log"
