apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "nvidia-packages-pvc"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "nvidia-packages-pv"
  fsType: "xfs"
  storageClassName: "gp2"
