apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nvidia-packages-pv"
  labels:
    type: "amazonEBS"
spec:
  capacity:
    storage: "50Gi"
  accessModes:
    - "ReadWriteMany"
  awsElasticBlockStore:
    volumeID: "vol-071bdd93e27358376"
    fsType: "xfs"
  storageClassName: "gp2"
