---

- name: Optional -- Update yum
  yum: name=* state=latest
  when: use_ubi == 'no' and use_s2i == 'no'

- name: Install EPEL
  yum: pkg=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: For non s2i/ubi builds, install yum prereqs
  yum:
    name:
      - automake
      - bzip2
      - cpp
      - gcc
      - gcc-c++
      - gcc-gfortran
      - git
      - gyp
      - libdb-devel
      - libgfortran
      - libquadmath
      - libquadmath-devel
      - libtool
      - make
      - patch
      - perl
      - perl-interpreter
      - perl-libs
      - python36-setuptools
      - wget
      - zlib-devel
    state: present
  when: use_ubi == 'no' and use_s2i == 'no'

- block:
  - name: << s2i/ubi >> Install basic yum pkgs that are available
    yum:
      name:
      - automake
      - bzip2
      - cpp
      - gcc
      - gcc-c++
      - gcc-gfortran
      - git
      - libdb-devel
      - libgfortran
      - libtool
      - make
      - patch
      - wget
      - zlib-devel

  - name: << s2i/ubi >> Clone gyp
    git:
      repo: https://chromium.googlesource.com/external/gyp
      dest: /tmp
      version: '{{ gyp_version }}'

  - name: << s2i/ubi >> Install gyp
    shell: |
      cd /tmp/gyp
      python3 setup.py install

  - name: << s2i/ubi >> Remove gyp build repo
    command: rm /tmp/gyp

  when: use_ubi == 'yes' or use_s2i == 'yes'
