---

- name: Install NumPy
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    CC="gcc -lblas -lgfortran" python3 setup.py install --prefix={{ NUMPY_INSTALL_DIR }}
  environment:
    PYTHONPATH: '{{ PYTHONPATH }}'
    LD_LIBRARY_PATH: '{{ FFTW_RHEL7_LIBRARY_DIR }}:{{ FFTW_RHEL8_LIBRARY_DIR }}'
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no'

- name: Install NumPy
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    python3 setup.py install --prefix={{ NUMPY_INSTALL_DIR }}
  environment:
    PYTHONPATH: '{{ PYTHONPATH }}'
    LD_LIBRARY_PATH: '{{ OPENBLAS_LIBRARY_DIR }}'
  when: USE_FFTW == 'no' and USE_OPENBLAS == 'yes'
