---

- name: Create NumPy 'site-packages' install folder so that NumPy can write to it
  file:
    state: directory
    path: '{{ NUMPY_INSTALL_DIR }}/lib/python3.6/site-packages'

- name: Install NumPy
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    CC="gcc -lblas -lgfortran" python3 setup.py install --prefix={{ NUMPY_INSTALL_DIR }}
  environment:
    PYTHONPATH: '{{ PYTHONPATH }}:{{ NUMPY_INSTALL_DIR }}/lib/python3.6/site-packages'
    LD_LIBRARY_PATH: '{{ BLAS_LIB_DIRS }}'
  when: USE_FFTW == 'yes' and USE_OPENBLAS == 'no'

- name: Install NumPy
  shell: |
    cd {{ NUMPY_BUILD_DIR }}
    python3 setup.py install --prefix={{ NUMPY_INSTALL_DIR }}
  environment:
    PYTHONPATH: '{{ PYTHONPATH }}:{{ NUMPY_INSTALL_DIR }}/lib/python3.6/site-packages'
    LD_LIBRARY_PATH: '{{ BLAS_LIB_DIRS }}'
  when: USE_FFTW == 'no' and USE_OPENBLAS == 'yes'
