---

# Install CMake
- name: Install CMake with pip3
  pip:
    executable: pip3
    name: cmake

# Install meson
- name: Install meson with pip3
  pip:
    executable: pip3
    name: meson

# Install ninja
- name: Install ninja with pip3
  pip:
    executable: pip3
    name: ninja

# Install XZ on RHEL 7 (for unarchiving mesa)
- name: Install XZ on RHEL 7
  yum:
    name: xz
  when: rhel_version == '7'

# Install XZ on RHEL 8 (for unarchiving mesa)
- name: Install XZ on RHEL 8
  dnf:
    name: xz
  when: rhel_version == '8'

# Remove existing build dirs
- name: Remove existing build dirs for libXmu, libXi, libX11, libXrandr, freeglut, mesa, xkbcommon
  file:
    state: absent
    path: '{{ item }}'
  with_items: 
    - '{{ libXmu_build_dir }}'
    - '{{ libX11_build_dir }}'
    - '{{ libXi_build_dir }}'
    - '{{ libXrandr_build_dir }}'
    - '{{ freeglut_build_dir }}'
    - '{{ mesa_build_dir }}'
    - '{{ xkbcommon_build_dir }}'

# Create build directory for each lib
- name: Create build dirs for libXmu, libXi, libX11, libXrandr, freeglut, mesa, xkbcommon
  file:
    state: directory
    path: '{{ item }}'
  with_items: 
    - '{{ libXmu_build_dir }}'
    - '{{ libX11_build_dir }}'
    - '{{ libXi_build_dir }}'
    - '{{ libXrandr_build_dir }}'
    - '{{ freeglut_build_dir }}'
    - '{{ mesa_build_dir }}'
    - '{{ xkbcommon_build_dir }}'

# Get libXmu
- name: Get libXmu from X.org
  unarchive:
    src: 'https://www.x.org/releases/individual/lib/libXmu-{{ libXmu_version }}.tar.gz'
    dest: '{{ libXmu_build_dir }}'
    remote_src: yes

# Get libX11
- name: Get libX11 from X.org
  unarchive:
    src: 'https://www.x.org/releases/individual/lib/libX11-{{ libX11_version }}.tar.gz'
    dest: '{{ libX11_build_dir }}'
    remote_src: yes

# Get libXi
- name: Get libXi from X.org
  unarchive:
    src: 'https://www.x.org/releases/individual/lib/libXi-{{ libXi_version }}.tar.gz'
    dest: '{{ libXi_build_dir }}'
    remote_src: yes

# Get libXrandr
- name: Get libXrandr from X.org
  unarchive:
    src: 'https://www.x.org/releases/individual/lib/libXrandr-{{ libXrandr_version }}.tar.gz'
    dest: '{{ libXrandr_build_dir }}'
    remote_src: yes

# Get freeglut
- name: Get freeglut from Source Forge
  unarchive:
    src: 'https://sourceforge.net/code-snapshots/svn/f/fr/freeglut/code/freeglut-code-r1859-trunk-freeglut-freeglut.zip'
    dest: '{{ freeglut_build_dir }}'
    remote_src: yes

# Get mesa
- name: Get mesa from freedesktop.org
  unarchive:
    src: 'https://mesa.freedesktop.org/archive/mesa-{{ mesa_version }}.tar.xz'
    dest: '{{ mesa_build_dir }}'
    remote_src: yes

# Get xkbcommon
- name: Get xkbcommon from git
  git:
    repo: https://github.com/xkbcommon/libxkbcommon.git
    version: '{{ xkbcommon_version }}'
    dest: '{{ xkbcommon_build_dir }}'

# Configure libXmu
- name: Configure libXmu
  shell: |
    cd '{{ libXmu_build_dir }}'
    ./configure

# Build libXmu
- name: Make libXmu
  make:
    chdir: '{{ libXmu_build_dir }}'
    target: all

# Install libXmu
- name: Install libXmu
  make:
    chdir: '{{ libXmu_build_dir }}'
    target: install

# Configure libXi
- name: Configure libXi
  shell: |
    cd '{{ libXi_build_dir }}'
    ./configure

# Build libXi
- name: Make libXi
  make:
    chdir: '{{ libXi_build_dir }}'
    target: all

# Install libXi
- name: Install libXi
  make:
    chdir: '{{ libXi_build_dir }}'
    target: install

# Configure libXrandr
- name: Configure libXrandr
  shell: |
    cd '{{ libXrandr_build_dir }}'
    ./configure

# Build libXrandr
- name: Make libXrandr
  make:
    chdir: '{{ libXrandr_build_dir }}'
    target: all

# Install libXrandr
- name: Install libXrandr
  make:
    chdir: '{{ libXrandr_build_dir }}'
    target: install

# Configure libX11
- name: Configure libX11
  shell: |
    cd '{{ libX11_build_dir }}'
    ./configure

# Build libX11
- name: Make libX11
  make:
    chdir: '{{ libX11_build_dir }}'
    target: all

# Install libX11
- name: Install libX11
  make:
    chdir: '{{ libX11_build_dir }}'
    target: install

# Prepare to build mesa
- name: Create build sub folder for mesa
  file:
    state: directory
    path: '{{ mesa_build_dir }}/build'

# Use meson+ninja to build and install mesa
- name: Use meson to build mesa and ninja to install it
  shell: |
    cd '{{ mesa_build_dir }}/build'
    meson ..
    ninja install

# Configure, build, and install libxkbcommon
- name: Configure, build, and install xkbcommon
  shell: |
    cd '{{ xkbcommon_build_dir }}'
    meson setup build
    ninja -C build

# Create freeglut Makefile
- name: Create freeglut Makefile using CMake
  shell: |
    cd '{{ freeglut_build_dir }}'
    cmake . -DFREEGLUT_BUILD_DEMOS=OFF -DFREEGLUT_WAYLAND=OFF -DFREEGLUT_BUILD_SHARED_LIBS=ON -DFREEGLUT_BUILD_STATIC_LIBS=ON

# Build freeglut
- name: Make freeglut
  make:
    chdir: '{{ freeglut_build_dir }}'
    target: all

# Install freeglut
- name: Install freeglut
  make:
    chdir: '{{ freeglut_build_dir }}'
    target: install
