apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make a TensorFlow build image in RHEL 7 using a pip repo TensorFlow"
    tags: "tensorflow-pip-build-image-rhel7-gpu"
  name: "tensorflow-pip-build-image-rhel7-gpu"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "tensorflow-pip-build-image-rhel7-gpu" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "TensorFlow/Dockerfiles/default/rhel7/gpu/Dockerfile.openshift_rhel7_cuda10"
        pullSecret:
          name: "${PULL_SECRET}"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${IMAGESTREAM_NAME}:latest"
    nodeSelector:
      beta.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${IMAGESTREAM_NAME}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/image-registry"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-pip-rhel7-gpu"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "g3.xlarge"
- description: "Pull secret"
  name: "PULL_SECRET"
  value: "openshift-image-registry-pull-secret"
  required: true
