FROM registry.access.redhat.com/rhscl/s2i-core-rhel7
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>
MAINTAINER Subin Modeel <smodeel@redhat.com>
ENV LANG=en_US.utf8
USER root
ENV BUILDER_VERSION 1.0

LABEL io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"

COPY ./s2i/bin/ /usr/libexec/s2i
ADD entrypoint /entrypoint
RUN chmod +x /entrypoint

EXPOSE 8080

ENV HOME /home/$NB_USER

USER 1001

WORKDIR /workspace

ENTRYPOINT ["/entrypoint"]
