---

- hosts: localhost
  connection: local
  become: yes

  vars:
    RHEL_VERSION: '{{ rhel_version | default("7") }}'
    BAZEL_VERSION: '{{ bazel_version | default("0.25.2") }}'
    USE_S2I: '{{ use_s2i | default("no") }}'
    USE_GPU: '{{ use_gpu | default("no") }}'
    CUDA_VERSION: '{{ cuda_version | default("10.1") }}'
    CUDA_NETWORK_RPM: '{{ cuda_rpm | default("") }}'
    NCCL_NETWORK_RPM: '{{ nccl_rpm | default("") }}'

  roles:

    # Install python36
    - role: rhel_python36

    # Install pip
    - role: python36_pip

    # Install NumPy prereqs
    - role: python36_numpy

    # Install Bazel
    - role: bazel

    # Install TensorFlow prereqs
    - role: tensorflow

    # Build BLAS and LAPACK by hand (since UBI/s2i yum repos do not contain BLAS or LAPACK)
    - role: s2i_blas_lapack
      when: USE_S2I == 'yes'

    # Install CBLAS
    - role: cblas

    # Install GPU prerequisites
    - role: cuda
      when: USE_GPU == 'yes'
