---

- hosts: localhost
  connection: local
  become: yes

  vars:
    rhel_ver: '{{ rhel_version | default("7") }}'
    bazel_ver: '{{ bazel_version | default("0.26.1") }}'
    s2i_ubi: '{{ use_s2i_ubi | default("no") }}'
    gpu: '{{ use_gpu | default("no") }}'
    cuda_ver: '{{ cuda_version | default("10.1") }}'
    cuda_network_rpm: '{{ cuda_rpm | default("") }}'

  roles:

    # Install python3
    - role: rhel_python3

    # Install pip
    - role: python3_pip

    # Install NumPy prereqs
    - role: python3_numpy

    # Install Bazel
    - role: bazel

    # Install TensorFlow prereqs
    - role: tensorflow

    # Build BLAS and LAPACK by hand (since UBI/s2i yum repos do not contain BLAS or LAPACK)
    - role: s2i_blas_lapack
      when: s2i_ubi == 'yes'

    # Install CBLAS
    - role: cblas

    # Install GPU prerequisites
    - role: cuda
      when: gpu == 'yes'
