---

- hosts: localhost
  connection: local
  become: yes

  vars:
    RHEL_VERSION: '{{ rhel_version | default("7") }}'
    BAZEL_VERSION: '{{ bazel_version | default("0.25.2") }}'

  roles:

    # Install python36
    - rhel_python36

    # Install pip
    - python36_pip

    # Install NumPy prereqs
    - python36_numpy

    # Install Bazel
    - bazel

    # Install TensorFlow prereqs
    - tensorflow

    # Install CBLAS
    - cblas
