---

- hosts: localhost
  connection: local
  become_user: root

  vars:
    rhel_ver: '{{ rhel_version | default("7") }}'
    bazel_ver: '{{ bazel_version | default("0.26.1") }}'
    use_ubi: '{{ ubi | default("yes") }}'

  roles:

    # Install python3
    - role: rhel_python3
      when: (use_ubi == 'no' and rhel_version == '7') or (rhel_version == '8')

    # Install pip
    - role: python3_pip

    # Install NumPy prereqs
    - role: python3_numpy

    # Install Bazel
    - role: bazel

    # Install TensorFlow prereqs
    - role: tensorflow

    # Build BLAS, LAPACK, and CBLAS from source
    - role: blas
