apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make FFTW build image"
    tags: "fftw-build-image-rhel8"
  name: "fftw-build-image-rhel8"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "fftw-build-image-rhel8" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "OpenBLAS/Dockerfiles/Dockerfile.openshift_rhel8"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${IMAGESTREAM_NAME}:latest"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${IMAGESTREAM_NAME}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/image-registry"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "fftw-rhel8"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
