---

# If we're going to use the AWS cli tool, then execute the 'get_cudnn_from_s3_with_awscli'
# role; otherwise, execute 'get_cudnn_from_url'
- include_role:
    name: get_cudnn_from_s3_with_awscli
  when: use_awscli == 'yes'

- include_role:
    name: get_cudnn_from_url
  when: use_awscli == 'no'

# Next step is to move all the files from cuDNN to their appropriate paths under the
# {{ cuda_path }} folder
- name: Move cudnn.h to {{ cuda_path }}/include
  shell: mv '{{ cudnn_download_dir }}/include/cudnn.h' '{{ cuda_path }}/include/cudnn.h'

- name: Move cuDNN libs to {{ cuda_path }}/lib64
  shell: mv '{{ cudnn_download_dir }}/lib64/*' '{{ cuda_path }}/lib64/'

# Finally, do some clean up: Remove the temporary download dir because we don't need
# it anymore
- name: Cleanup --> Remove temp dir {{ cudnn_download_dir }}
  file:
    state: absent
    path: '{{ cudnn_download_dir }}'
