apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to run FFTW build job"
    tags: "fftw-nfd-build-job"
  name: "fftw-nfd-build-job"
objects:
- apiVersion: "batch/v1"
  kind: "Job"
  metadata:
    name: "${APP_NAME}"
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    template:
      metadata:
        name: "${APP_NAME}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${REGISTRY}/${NAMESPACE}/${IMAGESTREAM_NAME}:latest"
          command: ["/usr/libexec/s2i/run"]
        restartPolicy: "Never"
        nodeSelector:
          beta.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "fftw-rhel7"
  required: true 
- description: "FFTW app name"
  name: "APP_NAME"
  from: '[A-Z0-9]{20}'
  value: "fftw-app"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "Current project (i.e., namespace)"
  name: "NAMESPACE"
  from: '[A-Z0-9]{15}'
  value: "fftw"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
  
