apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make OpenBLAS build image"
    tags: "fftw-nfd-build-image-rhel7"
  name: "fftw-nfd-build-image-rhel7"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "fftw-nfd-build-image-rhel7" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "FFTW/Dockerfiles/Dockerfile.openshift_rhel7"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${IMAGESTREAM_NAME}:latest"
    nodeSelector:
      beta.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${IMAGESTREAM_NAME}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/image-registry"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "fftw-rhel7"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "Use AVX -- true or false"
  name: "USE_AVX"
  from: '[A-Z]{5}'
  value: "true"
- description: "Use AVX2 -- true or false"
  name: "USE_AVX2"
  from: '[A-Z]{5}'  
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
  
