---

# Install TensorFlow requirements
- name: Install requirements for building the to-be-generated TensorFlow pip package
  pip:
    name:
      - absl-py
      - keras_applications
      - keras_preprocessing
      - mock
      - six 
      - wheel
    executable: pip3

- name: RHEL 7 --> Install remaining TensorFlow requirements
  yum: pkg=glibc
  when: RHEL_VERSION == '7'

- name: RHEL 8 --> Install remaining TensorFlow requirements
  dnf: pkg=glibc
  when: RHEL_VERSION == '8'
