apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to run FFTW build job with CPU Manager"
    tags: "fftw-nfd-cpu-manager-build-job"
  name: "fftw-nfd-cpu-manager-build-job"
objects:
- apiVersion: "batch/v1"
  kind: "Job"
  metadata:
    name: "${APP_NAME}"
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    template:
      metadata:
        name: "${APP_NAME}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${REGISTRY}/${NAMESPACE}/${IMAGESTREAM_NAME}:latest"
          command: ["/usr/libexec/s2i/run"]
          args: ["${THREAD_VALUES}"]
        restartPolicy: "Never"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "beta.kubernetes.io/instance-type"
                  operator: "In"
                  values:
                  - "${INSTANCE_TYPE}"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
        resources:
          requests:
            cpu: "${N_CPUS}"
            memory: "${MEMORY_SIZE}"
          limits:
            cpu: "${N_CPUS}"
            memory: "${MEMORY_SIZE}"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "fftw-rhel7"
  required: true 
- description: "FFTW CPU Manager app name"
  name: "APP_NAME"
  from: '[A-Z0-9]{20}'
  value: "fftw-app-cpu-manager"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "Current project (i.e., namespace)"
  name: "NAMESPACE"
  from: '[A-Z0-9]{15}'
  value: "fftw"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
  required: true
- description: "Number of CPUs to use"
  name: "N_CPUS"
  value: "1"
  required: true
- description: "Memory size"
  name: "MEMORY_SIZE"
  value: "1G"
  required: true
- description: "Thread values"
  name: "THREAD_VALUES"
  required: false
