---

- name: RHEL 7 --> Install lspci
  yum: pkg=pciutils
  when: RHEL_VERSION == "7"

- name: RHEL 8 --> Install lspci
  dnf: pkg=pciutils
  when: RHEL_VERSION == "8"

- block:
  - name: 'End play if CUDA network rpm is missing'
    debug:
      msg: 'Missing CUDA network rpm. Find your network rpm here: https://developer.nvidia.com/cuda-toolkit-archive'

  - meta: end_play
  when: CUDA_NETWORK_RPM == ""

- name: Check for a CUDA-capable GPU
  shell: 'lspci | grep -i nvidia'
  register: nvidia_lspci_output
  ignore_errors: yes

- block:
  - name: 'End play if user does not have a CUDA-capable GPU'
    debug:
      msg: 'No CUDA capable GPU was found. Aborting.'

  - meta: end_play
  when: nvidia_lspci_output.stdout == ""

- debug:
    var: CUDA_NETWORK_RPM

- name: Create CUDA tmp dir
  file:
    state: directory
    path: '{{ CUDA_TMP_DIR }}'

- name: Download CUDA toolkit network rpm
  get_url:
    url: '{{ CUDA_NETWORK_RPM }}'
    dest: '{{ CUDA_TMP_DIR }}'

- name: Find CUDA rpm
  find:
    paths: '{{ CUDA_TMP_DIR }}'
    patterns: '*.rpm'
  register: cuda_rpms

- name: Install CUDA rpm
  yum:
    name: item.path
  with_items: '{{ cuda_rpms["files"] }}'

- name: Yum clean expire-cache
  command: yum clean expire-cache

- name: Install CUDA
  yum:
    name:
      - cuda
