---

# Remove any existing TensorFlow build dirs
- name: Remove TensorFlow build dir (if it exists)
  file:
    state: absent
    path: '{{ TENSORFLOW_BUILD_DIR }}'

# Make TensorFlow build dir
- name: Make TensorFlow build dir
  file:
    state: directory
    path: '{{ TENSORFLOW_BUILD_DIR }}'

# Print out where it's being saved to
- debug:
    var: TENSORFLOW_BUILD_DIR

# Remove any existing NumPy build dirs
- name: Remove NumPy build dir (if it exists)
  file:
    state: absent
    path: '{{ NUMPY_BUILD_DIR }}'

# Make NumPy build dir
- name: Make NumPy build dir
  file:
    state: directory
    path: '{{ NUMPY_BUILD_DIR }}'

# Print out where it's being saved to
- debug:
    var: NUMPY_BUILD_DIR

# Remove any existing NumPy install dirs
- name: Remove NumPy install dir (if it exists)
  file:
    state: absent
    path: '{{ NUMPY_INSTALL_DIR }}'

# Make NumPy install dir
- name: Make NumPy install dir
  file:
    state: directory
    path: '{{ NUMPY_INSTALL_DIR }}/lib64/python3.6/site-packages'

# Print out where the library will be installed
- debug:
    var: NUMPY_INSTALL_DIR
