apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make a TensorFlow RHEL 8 build image with an FFTW NumPy backend"
    tags: "tensorflow-fftw-build-image-rhel8"
  name: "tensorflow-fftw-build-image-rhel8"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "tensorflow-fftw-build-image-rhel8" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    dockerImageRepository: "registry.redhat.io/rhel8/s2i-core"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "TensorFlow/Dockerfiles/FFTW_backend/Dockerfile.openshift_rhel8"
        pullSecret:
          name: "${PULL_SECRET}"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${IMAGESTREAM_NAME}:latest"
    nodeSelector:
      beta.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${IMAGESTREAM_NAME}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/image-registry"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-fftw-rhel8"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
  required: true
- description: "Pull secret"
  name: "PULL_SECRET"
  required: true
