---

- hosts: localhost
  become: yes
  connection: local

  vars:
    rhel_ver: '{{ rhel_version | default("7") }}'
    yum_update: '{{ update_yum | default("yes") }}'
    dnf_update: '{{ update_dnf | default("yes") }}'

  tasks:
  # XXX:TODO --> For UBI-7, `yum update` is broken.
  #- name: yum update (if using RHEL 7)
  #  yum: name=* state=latest
  #  when: RHEL_VERSION == "7"

  - name: Install EPEL (if using RHEL 7)
    yum: pkg=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    when: rhel_ver == "7"

  - name: Install yum prereqs (if using RHEL 7)
    yum:
      name:
        - bc
        - binutils
        - cpp
        - diffutils
        - gcc
        - gcc-c++
        - gcc-gfortran
        - libgomp
        - libquadmath
        - libquadmath-devel
        - libtool
        - make
        - patch
        - yum-utils
      state: present
    when: rhel_ver == "7"

  - name: dnf update (if using RHEL 8)
    dnf: name=* state=latest
    when: rhel_ver == "8" and dnf_update == "yes"

  - name: Install dnf prereqs (if using RHEL 8)
    dnf:
      name:
        - binutils
        - cpio
        - cpp
        - diffutils
        - gcc
        - gcc-c++
        - gcc-gfortran
        - libgomp
        - libquadmath
        - libquadmath-devel
        - libtool
        - make
        - patch
        - yum-utils
      state: present
    when: rhel_ver == "8"
