---

- name: Remove {{ nccl_agnostic_install_path }} if it exists
  file:
    state: absent
    path: '{{ nccl_agnostic_install_path }}'

- name: Create {{ nccl_agnostic_install_path }}
  file:
    state: directory
    path: '{{ nccl_agnostic_install_path }}'

- name: Copy {{ ebs_dir }}/nccl contents to {{ nccl_agnostic_install_path }}
  shell: cp '{{ ebs_dir }}/nccl/*' '{{ nccl_agnostic_install_path }}'
