apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make OpenBLAS build image"
    tags: "openblas-gemm"
  name: "openblas-gemm"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "openblas-gemm-app" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "OpenBLAS/Dockerfiles/Dockerfile.openshift"
    output: 
      to:
        kind: "DockerImage"
        name: "image-registry-openshift-image-registry.apps.cpacheco-gpu-cluster02.devcluster.openshift.com:5000/openshift-image-registry/openblas-rhel7:latest"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "openblas-gemm-is"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "image-registry-openshift-image-registry.apps.cpacheco-gpu-cluster02.devcluster.openshift.com:5000/openshift-image-registry"
