apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to run a TensorFlow AVX512 build job with CPU Manager"
    tags: "tensorflow-avx512-cpu-manager-build-job"
  name: "tensorflow-avx512-cpu-manager-build-job"
objects:
- apiVersion: "batch/v1"
  kind: "Job"
  metadata:
    name: "${APP_NAME}"
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    template:
      metadata:
        name: "${APP_NAME}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${REGISTRY}/${NAMESPACE}/${IMAGESTREAM_NAME}:latest"
          command: ["/usr/libexec/s2i/run"]
          env:
            - name: "RHEL_VERSION"
              value: "${RHEL_VERSION}"
            - name: "DEVICE"
              value: "cpu"
            - name: "NUM_DEVICES"
              value: "${NUM_CPUS}"
            - name: "CC"
              value: "${CC}"
            - name: "WHICH_SOURCE"
              value: "none"
            - name: "PYTHON_EXECUTABLE"
              value: "${PYTHON_EXECUTABLE}"
        restartPolicy: "Never"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "feature.node.kubernetes.io/cpuid-AVX512BW"
                  operator: "Exists"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
              - matchExpressions:
                - key: "feature.node.kubernetes.io/cpuid-AVX512CD"
                  operator: "Exists"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
              - matchExpressions:
                - key: "feature.node.kubernetes.io/cpuid-AVX512DQ"
                  operator: "Exists"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
              - matchExpressions:
                - key: "feature.node.kubernetes.io/cpuid-AVX512F"
                  operator: "Exists"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
              - matchExpressions:
                - key: "feature.node.kubernetes.io/cpuid-AVX512VL"
                  operator: "Exists"
                - key: "cpumanager"
                  operator: "In"
                  values:
                  - "true"
        resources:
          requests:
            cpu: "${N_CPUS}"
            memory: "${MEMORY_SIZE}"
          limits:
            cpu: "${N_CPUS}"
            memory: "${MEMORY_SIZE}"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  required: true 
- description: "TensorFlow app name"
  name: "APP_NAME"
  from: '[A-Z0-9]{20}'
  value: "tensorflow-s2i-benchmark-app-avx512-cpu-manager"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "Current project (i.e., namespace)"
  name: "NAMESPACE"
  from: '[A-Z0-9]{15}'
  value: "openshift-image-registry"
  required: true
- description: "RHEL version to use"
  name: "RHEL_VERSION"
  from: '[0-9]{1}'
  value: "7"
  required: true
- description: "Path to Python executable"
  name: "PYTHON_EXECUTABLE"
  value: "/usr/bin/python3"
  required: true
- description: "Number of CPUs to use"
  name: "NUM_CPUS"
  value: "1"
  required: true
- description: "Memory size"
  name: "MEMORY_SIZE"
  value: "1G"
  required: true
- description: "Path to gcc"
  name: "CC"
  value: "/usr/bin/gcc"
  required: true
