---

- hosts: localhost
  connection: local

  vars:

    # Add variable to define whether to use RHEL 7 or 8
    rhel_version: '{{ rhel_ver | default("7") }}'

    # This is the path to the CUDA installation you want to use
    cuda_path: '{{ cuda_install_path | default("/usr/local/cuda") }}'

    # This is the URL where Ansible will download cuDNN
    cudnn_url: '{{ cudnn | default("") }}'

    # Check GPU
    gpu_check: '{{ gpu_check | default("yes") }}'

  roles:

    # Check for NVIDIA (CUDA-capable) GPU
    - role: check_gpu
      when: gpu_check == 'yes'

    # Install CUDNN
    - role: install_cudnn
