FROM nvidia/cuda:10.1-base-ubi8
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>
ENV LANG=en_US.utf8
USER root
ENV BUILDER_VERSION 1.0

# Ansible version
ENV ANSIBLE_GIT_VERSION=v2.8.3

# RHEL version (for building FFTW)
ENV RHEL_VERSION=8

# Set up labels
LABEL io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"
LABEL io.openshift.expose-services="8080:http"

# Copy s2i assemble + run
COPY TensorFlow/.s2i_fftw/bin/ /usr/libexec/s2i

# Set timeout for dnf (in seconds) to prevent Curl timeout errors w/ dnf
ENV DNF_TIMEOUT=300
RUN sed -i "/[main]/a timeout=${DNF_TIMEOUT}" /etc/dnf/dnf.conf

# Set top directory
ENV TOPDIR=/home

# Set playbook paths
ENV FFTW_PREREQS_PLAYBOOK=${TOPDIR}/fftw_package_installation
ENV TF_PREREQS_PLAYBOOK=${TOPDIR}/tensorflow_package_installation
ENV FFTW_INSTALLATION=${TOPDIR}/playbooks/FFTW_installation
ENV TENSORFLOW_INSTALLATION=${TOPDIR}/playbooks/TensorFlow_installation
ENV TENSORFLOW_BENCHMARKS=${TOPDIR}/playbooks/TensorFlow_benchmarks

# Create folders for playbooks and folder for playbooks cache
RUN mkdir -p ${FFTW_PREREQS_PLAYBOOK} && \
    mkdir -p ${TF_PREREQS_PLAYBOOK} && \
    mkdir -p ${FFTW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_BENCHMARKS} && \
    mkdir -p ${TOPDIR}/.cache

# Copy playbooks and scripts
COPY helper_scripts/Ansible/install_ansible_from_source.sh ${TOPDIR}
COPY FFTW/playbooks/package_installation ${FFTW_PREREQS_PLAYBOOK}
COPY TensorFlow/playbooks/package_installation ${TF_PREREQS_PLAYBOOK}
COPY FFTW/playbooks/FFTW_installation ${FFTW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_installation ${TENSORFLOW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_benchmarks ${TENSORFLOW_BENCHMARKS}

# Put on port 8080
EXPOSE 8080

# Set up symbolic linking for Python so that TensorFlow build doesn't fail when s2i script is called
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install Ansible
RUN cd ${TOPDIR} && \
    sh install_ansible_from_source.sh ${ANSIBLE_GIT_VERSION} && \
    rm install_ansible_from_source.sh

# Install FFTW + TensorFlow prerequisites via Ansible
RUN cd ${FFTW_PREREQS_PLAYBOOK} && \
    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '8'}" && \
    cd ${TF_PREREQS_PLAYBOOK} && \
    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '8', use_s2i_ubi: 'yes'}"

# Give user permissions to modify the 'macros' file + other files to run tests
RUN chmod 777 /usr/libexec/s2i/run && \
    chmod g=u /etc/passwd /etc/group && \
    mkdir -p ${TOPDIR}/.ansible/tmp && \
    chmod 777 ${TOPDIR}/.ansible/tmp && \
    chmod 777 ${TOPDIR}/.ansible && \
    chmod -R 777 ${TOPDIR}/.cache && \
    chmod 777 ${TOPDIR}

# Set Ansible remote tmp
RUN echo "remote_tmp = ${TOPDIR}/.ansible/tmp" >> ${FFTW_INSTALLATION}/ansible.cfg && \
    echo "remote_tmp = ${TOPDIR}/.ansible/tmp" >> ${TENSORFLOW_INSTALLATION}/ansible.cfg

# Add 'default' user
RUN groupadd -r default && \
    useradd --no-log-init -u 1001 -d ${TOPDIR} -g default default

# Set user to 'default'
USER default

WORKDIR ${TOPDIR}

CMD ["/usr/libexec/s2i/usage"]
