FROM registry.redhat.io/rhel8/s2i-core
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>
ENV LANG=en_US.utf8
USER root
ENV BUILDER_VERSION 1.0

# Ansible version
ENV ANSIBLE_GIT_VERSION=v2.8.3

# RHEL version (for building FFTW)
ENV RHEL_VERSION=8

# Set up labels
LABEL io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"
LABEL io.openshift.expose-services="8080:http"

# Copy s2i assemble + run
COPY TensorFlow/.s2i_fftw/bin/ /usr/libexec/s2i

# Set playbook paths
ENV FFTW_PREREQS_PLAYBOOK=${HOME}/fftw_package_installation
ENV TF_PREREQS_PLAYBOOK=${HOME}/tensorflow_package_installation
ENV FFTW_INSTALLATION=${HOME}/playbooks/FFTW_installation
ENV TENSORFLOW_INSTALLATION=${HOME}/playbooks/TensorFlow_installation
ENV TENSORFLOW_BENCHMARKS=${HOME}/playbooks/TensorFlow_benchmarks

# Create folders for playbooks and folder for playbooks cache
RUN mkdir -p ${FFTW_PREREQS_PLAYBOOK} && \
    mkdir -p ${TF_PREREQS_PLAYBOOK} && \
    mkdir -p ${FFTW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_BENCHMARKS} && \
    mkdir -p ${HOME}/.cache

# Copy playbooks and scripts
COPY helper_scripts/Ansible/install_ansible_from_source.sh ${HOME}
COPY FFTW/playbooks/package_installation ${FFTW_PREREQS_PLAYBOOK}
COPY TensorFlow/playbooks/package_installation ${TF_PREREQS_PLAYBOOK}
COPY FFTW/playbooks/FFTW_installation ${FFTW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_installation ${TENSORFLOW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_benchmarks ${TENSORFLOW_BENCHMARKS}

# Put on port 8080
EXPOSE 8080

# Install Ansible
RUN sh install_ansible_from_source.sh ${ANSIBLE_GIT_VERSION} && \
    rm install_ansible_from_source.sh

# Install FFTW prerequisites via Ansible
RUN cd ${FFTW_PREREQS_PLAYBOOK} && \
    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '8'}" && \
    cd .. && \
    rm -rf ${FFTW_PREREQS_PLAYBOOK}

# Install TensorFlow prerequisites via Ansible
RUN cd ${TF_PREREQS_PLAYBOOK} && \
    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '8', use_s2i: 'yes', use_gpu: 'yes', cuda_rpm: 'https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-10.0.130-1.x86_64.rpm'}" && \
    cd .. && \
    rm -rf ${TF_PREREQS_PLAYBOOK}

# Set up symbolic linking for Python so that TensorFlow build doesn't fail when s2i script is called
RUN ln -s /usr/bin/python3 /usr/bin/python

# Give user permissions to modify the 'macros' file + other files to run tests
RUN chmod 777 /usr/libexec/s2i/run && \
    chmod g=u /etc/passwd /etc/group && \
    mkdir -p /opt/app-root/src/.ansible/tmp && \
    chmod 777 /opt/app-root/src/.ansible/tmp && \
    chmod 777 /opt/app-root/src/.ansible && \
    chmod -R 777 /opt/app-root/src/.cache && \
    chmod 777 /opt/app-root/src && \
    chmod 777 /opt/app-root

# Set Ansible remote tmp
RUN echo "remote_tmp = ${HOME}/.ansible/tmp" >> ${FFTW_INSTALLATION}/ansible.cfg && \
    echo "remote_tmp = ${HOME}/.ansible/tmp" >> ${TENSORFLOW_INSTALLATION}/ansible.cfg

# This default user is created in the openshift/base-centos7 image
USER 1001

WORKDIR ${HOME}

CMD ["/usr/libexec/s2i/usage"]
