FROM nvidia/cuda:10.0-base-ubi7
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>
ENV LANG=en_US.utf8
USER root
ENV BUILDER_VERSION 1.0

# RHEL version (for building FFTW)
ENV RHEL_VERSION=7

# Python version
ENV PYTHON_VERSION=3.6.9

# Ansible version
ENV ANSIBLE_VERSION=v2.8.6

# Set up labels
LABEL io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"
LABEL io.openshift.expose-services="8080:http"

# Copy s2i assemble + run
COPY TensorFlow/.s2i_fftw/bin/ /usr/libexec/s2i

# Put on port 8080
EXPOSE 8080

# Set timeout for yum (in seconds) to prevent Curl timeout errors w/ yum
ENV YUM_TIMEOUT=300
RUN sed -i "/[main]/a timeout=${YUM_TIMEOUT}" /etc/yum.conf

# Set app directory
ENV APPDIR="/benchmark_app"

# Set user
ENV USER=1001

# Set playbook paths
ENV FFTW_PREREQS_PLAYBOOK=${APPDIR}/playbooks/fftw_package_installation
ENV TF_PREREQS_PLAYBOOK=${APPDIR}/playbooks/tensorflow_package_installation
ENV FFTW_INSTALLATION=${APPDIR}/playbooks/FFTW_installation
ENV TENSORFLOW_INSTALLATION=${APPDIR}/playbooks/TensorFlow_installation
ENV TENSORFLOW_MODELS=${APPDIR}/playbooks/TensorFlow_Models
ENV NCCL_INSTALLATION=${APPDIR}/playbooks/nccl_installation
ENV CUDNN_INSTALLATION=${APPDIR}/playbooks/cudnn_installation
ENV TENSORRT_INSTALLATION={$APPDIR}/playbooks/tensorrt_installation

# Set scripts path
ENV SCRIPTS=${APPDIR}/scripts

# Create folders for playbooks and folder for playbooks cache
RUN mkdir -p ${FFTW_PREREQS_PLAYBOOK} && \
    mkdir -p ${TF_PREREQS_PLAYBOOK} && \
    mkdir -p ${FFTW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_INSTALLATION} && \
    mkdir -p ${TENSORFLOW_MODELS} && \
    mkdir -p ${NCCL_INSTALLATION} && \
    mkdir -p ${CUDNN_INSTALLATION} && \
    mkdir -p ${TENSORRT_INSTALLATION} && \
    mkdir -p ${SCRIPTS} && \
    mkdir -p ${APPDIR}/.cache

# Copy playbooks and scripts
COPY FFTW/playbooks/package_installation ${FFTW_PREREQS_PLAYBOOK}
COPY TensorFlow/playbooks/package_installation ${TF_PREREQS_PLAYBOOK}
COPY FFTW/playbooks/FFTW_installation ${FFTW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_installation ${TENSORFLOW_INSTALLATION}
COPY TensorFlow/playbooks/TensorFlow_Models ${TENSORFLOW_MODELS}
COPY TensorFlow/playbooks/nccl_installation ${NCCL_INSTALLATION}
COPY TensorFlow/playbooks/cudnn_installation ${CUDNN_INSTALLATION}
COPY TensorFlow/playbooks/tensorrt_installation ${TENSORRT_INSTALLATION}
COPY helper_scripts/Python/install_python_from_source.sh ${SCRIPTS}
COPY helper_scripts/Ansible/install_ansible_from_source.sh ${SCRIPTS}

# Create symlink for NumPy so that it can find endian.h
RUN yum -y install glibc glibc-devel && \
    ln -s /usr/include/endian.h /usr/include/sys/endian.h

# Install Python version ${PYTHON_VERSION} from source and Ansible version ${ANSIBLE_VERSION} from source
RUN cd ${SCRIPTS} && \
    sh install_python_from_source.sh ${PYTHON_VERSION} && \
    sh install_ansible_from_source.sh ${ANSIBLE_VERSION}

# Install FFTW + TensorFlow prerequisites via Ansible and pip3
RUN cd ${FFTW_PREREQS_PLAYBOOK} && \
    PYTHONPATH=/usr/lib/python2.7 ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '7', use_ubi: 'yes', update_yum: 'no', ansible_python_interpreter: '/usr/bin/python2.7'}" && \
    cd ${TF_PREREQS_PLAYBOOK} && \
    PYTHONPATH=/usr/lib/python2.7 ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '7', use_s2i_ubi: 'yes', ansible_python_interpreter: '/usr/bin/python2.7'}"

# Create and give user permissions to modify certain directories that are required to run the Ansible
# playbooks that are being pulled into this Dockerfile. Also allow /usr/local/cuda to be writable and
# allow /.aws to be writeable in case the user wants to use an AWS s3 bucket to download NCCL + cuDNN
RUN chmod -R 777 /usr/libexec/s2i && \
    chmod g=u /etc/passwd /etc/group && \
    chmod g=u /etc/subuid /etc/subgid && \
    mkdir -p ${APPDIR}/.ansible/tmp && \
    mkdir -p ${APPDIR}/.aws && \
    mkdir -p ${APPDIR}/.cache/bazel && \
    touch ${APPDIR}/.gitconfig && \
    chmod -R 777 /usr/local/cuda && \
    chmod -R 777 ${APPDIR}

# Set Ansible remote tmp
RUN echo "remote_tmp = ${APPDIR}/.ansible/tmp" >> ${FFTW_INSTALLATION}/ansible.cfg && \
    echo "remote_tmp = ${APPDIR}/.ansible/tmp" >> ${TENSORFLOW_INSTALLATION}/ansible.cfg && \
    echo "remote_tmp = ${APPDIR}/.ansible/tmp" >> ${TENSORFLOW_MODELS}/ansible.cfg

# Set work directory
WORKDIR ${APPDIR}

# Set user to '1001'
USER ${USER}

# Set CMD
CMD ["/usr/libexec/s2i/run"]
