---

# Remove existing CBLAS build directory
- name: Remove existing CBLAS build directory
  file:
    state: directory
    path: '{{ CBLAS_BUILD_DIR }}'

# Make libcblas instead of using libatlas.so
- name: Download CBLAS sources rather than using libatlas
  unarchive:
    src: http://www.netlib.org/blas/blast-forum/cblas.tgz
    dest: '{{ CBLAS_BUILD_DIR }}'
    remote_src: yes
    extra_opts: [--strip-components=1]

# Modify our Makefile such that we build a CBLAS shared object library
- name: Change line in CBLAS' Makefile.LINUX to point to where libblas.a is
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^BLLIB*'
    line: 'BLLIB = {{ BLAS_INSTALL_DIR }}/libblas.so'

- name: Change line in CBLAS' Makefile.LINUX to build a shared object library, rather than static
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^CBLIB*'
    line: 'CBLIB = ../lib/libcblas.so'

- name: Add -fPIC to CFLAGS in CBLAS' Makefile.LINUX
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^CFLAGS*'
    line: 'CFLAGS = -O3 -DADD_ -fPIC'

- name: Add -fPIC to FFLAGS in CBLAS' Makefile.LINUX
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^FFLAGS*'
    line: 'FFLAGS = -O3 -fPIC'

- name: Set ARCH in Makefile.LINUX to point to gcc
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^ARCH =*'
    line: 'ARCH = gcc'

- name: Set ARCHFLAGS in Makefile.Linux to use '-shared' and '-o'
  lineinfile:
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    regexp: '^ARCHFLAGS'
    line: 'ARCHFLAGS = -shared -o'

- name: Remove dummy Makefile.in
  file:
    state: absent
    path: '{{ CBLAS_BUILD_DIR }}/Makefile.in'

- name: Create symbolic link where we set Makefile.in = Makefile.LINUX
  file:
    state: link
    src: '{{ CBLAS_BUILD_DIR }}/Makefile.LINUX'
    dest: '{{ CBLAS_BUILD_DIR }}/Makefile.in'

# Make the library
- name: Make libcblas.so
  make:
    target: all
    chdir: '{{ CBLAS_BUILD_DIR }}'

# Move CBLAS headers to /usr/include
- name: Move cblas.h to /usr/include
  command: 'mv {{ CBLAS_BUILD_DIR }}/include/cblas.h /usr/include'

- name: Move cblas_f77.h to /usr/include
  command: 'mv {{ CBLAS_BUILD_DIR }}/include/cblas_f77.h /usr/include'

# Finally, move the shared object library to /usr/lib64 so it can be found by NumPy
- name: Move libcblas.so to /usr/lib64
  command: 'mv {{ CBLAS_BUILD_DIR }}/lib/libcblas.so {{ CBLAS_INSTALL_DIR }}/libcblas.so'
