---

###################################
#         Install package         #
###################################
- name: Install FFTW
  make:
    chdir: '{{ build_dir }}/FFTW'
    target: install
    params:
      destdir: '{{ install_dir }}'

###################################
#   Prepare for reorganization    #
###################################
- find:
    paths: '{{ install_dir }}/usr/local/include'
    patterns: '*.h'
  register: find_headers

- name: Reorganize header files location
  command: mv '{{ item["path"] }}' '{{ install_dir }}/include'
  with_items: '{{ find_headers["files"] }}'

- find:
    paths: '{{ install_dir }}/usr/local/lib'
    patterns: '*.so*'
  register: find_libs_so_versioned

- find:
    paths: '{{ install_dir }}/usr/local/lib'
    patterns: '*.a'
  register: find_libs_a

- name: Reorganize shared object libs location
  command: mv '{{ item["path"] }}' '{{ install_dir }}/lib'
  with_items: '{{ find_libs_so_versioned["files"] }}'

- name: Reorganize static object libs location
  command: mv '{{ item["path"] }}' '{{ install_dir }}/lib'
  with_items: '{{ find_libs_a["files"] }}'

###################################
#         For RHEL 7 only         #
###################################
- block:
  - name: RHEL 7 --> Reorganize symlink for libfftw.so
    command: mv '{{ install_dir }}/usr/local/lib/libfftw.so' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for librfftw.so
    command: mv '{{ install_dir }}/usr/local/lib/librfftw.so' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for libfftw.so.2
    command: mv '{{ install_dir }}/usr/local/lib/libfftw.so.2' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for librfftw.so.2
    command: mv '{{ install_dir }}/usr/local/lib/librfftw.so.2' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for libfftw_threads.so
    command: mv '{{ install_dir }}/usr/local/lib/libfftw_threads.so' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for librfftw_threads.so
    command: mv '{{ install_dir }}/usr/local/lib/librfftw_threads.so' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for libfftw_threads.so.2
    command: mv '{{ install_dir }}/usr/local/lib/libfftw_threads.so.2' '{{ install_dir }}/lib'

  - name: RHEL 7 --> Reorganize symlink for librfftw_threads.so.2
    command: mv '{{ install_dir }}/usr/local/lib/librfftw_threads.so.2' '{{ install_dir }}/lib'

  when: rhel_ver == '7'

###################################
#         For RHEL 8 only         #
###################################
- block:
  - name: RHEL 8 --> Reorganize symlink for libfftw3.so.3
    command: mv '{{ install_dir }}/usr/local/lib/libfftw3.so.3' '{{ install_dir }}/lib'

  - name: RHEL 8 --> Reorganize symlink for libfftw3_threads.so
    command: mv '{{ install_dir }}/usr/local/lib/libfftw3_threads.so' '{{ install_dir }}/lib'

  - name: RHEL 8 --> Reorganize symlink for libfftw3_threads.so.3
    command: mv '{{ install_dir }}/usr/local/lib/libfftw3_threads.so.3' '{{ install_dir }}/lib'

  - name: RHEL 8 --> Add symlink to create 'libfftw3.so'
    file:
      state: link
      src: '{{ install_dir }}/lib/libfftw3.so.3'
      dest: '{{ install_dir }}/lib/libfftw3.so'

  when: rhel_ver == '8'


###################################
#            Clean up             #
###################################
- name: Remove {{ install_dir }}/usr
  file:
    path: '{{ install_dir }}/usr'
    state: absent
