# This image is based on https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubi8/10.1/base/Dockerfile
FROM registry.redhat.io/rhel8/s2i-core
MAINTAINER "Courtney Pacheco <cpacheco@redhat.com>"

# Set NVIDIA environment vars
ENV CUDA_PACKAGE_VERSION=10-1

#<!-- taken from NVIDIA's Dockerfile -->
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_REQUIRE_CUDA="cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411"
#<!-- end -->

# Set PATH vars
#<!-- taken from NVIDIA's Dockerfile -->
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
#<!-- end -->

# Copy user's 'rhel8-Latest.repo'
COPY repos/rhel8-Latest.repo /etc/yum.repos.d/rhel8-Latest.repo

# Copy 'cuda repo'
COPY repos/rhel8-cuda.repo /etc/yum.repos.d/cuda.repo

# Install CUDA packages
RUN dnf clean all && \
    dnf -y install cuda-cudart-${CUDA_PACKAGE_VERSION} \
                   cuda-compat-${CUDA_PACKAGE_VERSION} \
                   cuda-core-${CUDA_PACKAGE_VERSION} \
                   cuda-cudart-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cufft-${CUDA_PACKAGE_VERSION} \
                   cuda-cufft-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cupti-${CUDA_PACKAGE_VERSION} \
                   cuda-curand-${CUDA_PACKAGE_VERSION} \
                   cuda-curand-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cusolver-${CUDA_PACKAGE_VERSION} \
                   cuda-cusolver-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-cusparse-${CUDA_PACKAGE_VERSION} \
                   cuda-cusparse-dev-${CUDA_PACKAGE_VERSION} \
                   cuda-misc-headers-${CUDA_PACKAGE_VERSION} \
                   libcublas-devel && \
    rm -rf /var/cache/dnf/*

# Disable CUDA and RHEL 8 repos (for now). User can re-enable them later if desired.
RUN dnf config-manager --disablerepo RHEL8-Latest && \
    dnf config-manager --disablerepo cuda
