apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make a TensorFlow 'AVX' build image using an FFTW NumPy"
    tags: "tensorflow-fftw-avx-build-image-rhel7"
  name: "tensorflow-fftw-avx-build-image-rhel7"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "tensorflow-fftw-avx-build-image-rhel7" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/redhat-performance/aimlperf_reg_tests.git"
        ref: "master"
    strategy: 
      type: "Docker"
      dockerStrategy:
        dockerfilePath: "TensorFlow/Dockerfiles/FFTW_backend/Dockerfile.openshift_rhel7"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${IMAGESTREAM_NAME}:latest"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "feature.node.kubernetes.io/cpuid-AVX"
              operator: "Exists"
              values:
              - "true"
          - matchExpressions:
            - key: "feature.node.kubernetes.io/cpuid-AVX2"
              operator: "DoesNotExist"
              values:
              - "true"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${IMAGESTREAM_NAME}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/image-registry"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-fftw-rhel7-avx"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
