---

- name: Find TensorFlow wheel file
  find:
    paths: '{{ TF_PIP_PACKAGE_LOCATION }}'
    patterns: '*.whl'
  register: tf_wheel_files

- name: Found wheel file(s)
  debug:
    var: item.path
  with_items: '{{ tf_wheel_files["files"] }}'

- name: Install TensorFlow
  pip:
    name: '{{ item["path"] }}'
    executable: pip3
    extra_args: '--target={{ TENSORFLOW_INSTALL_DIR }}'
  with_items: '{{ tf_wheel_files["files"] }}'

- name: Remove pip package
  file:
    state: absent
    path: '{{ TF_PIP_PACKAGE_LOCATION }}'
