---

- name: Find TensorFlow wheel file
  find:
    paths: /tmp/tensorflow_pkg
    patterns: '*.whl'
  register: tf_wheel_files

- name: Found wheel file(s)
  debug:
    var: item.path
  with_items: '{{ tf_wheel_files["files"] }}'

- name: Install TensorFlow
  pip:
    name: '{{ item["path"] }}'
    executable: pip3
  with_items: '{{ tf_wheel_files["files"] }}'
