---

- hosts: localhost
  become: yes
  connection: local

  vars:
    rhel_ver: '{{ rhel_version | default("7") }}'
    use_s2i: '{{ s2i | default("no") }}'
    use_ubi: '{{ ubi | default("no") }}'

  roles:
    # Installs OpenBLAS prerequisites on RHEL 7 for ubi/s2i and non-ubi/non-s2i images
    - role: rhel7
      when: rhel_ver == '7'

    # Installs OpenBLAS prerequisites on RHEL 8 for ubi/s2i and non-ubi/non-s2i images
    - role: rhel8
      when: rhel_ver == '8'
