---

- hosts: localhost
  connection: local

  vars:

    # This is the path to the CUDA installation you want to use
    cuda_path: '{{ cuda_install_path | default("/usr/local/cuda")'

    # This is the URL where Ansible will download the NCCL OS agnostic local installer
    nccl_agnostic_local_installer: '{{ nccl_installer | default("") }}'

    # This is where we will install NCCL to
    nccl_agnostic_install_path: '{{ nccl_install_path | default("/home/nccl") }}'

    # Set RHEL version
    rhel_version: '{{ rhel_ver | default("7") }}'

    # Check GPU
    gpu_check: '{{ gpu_check | default("yes") }}'

    # Use EBS to get NCCL?
    use_ebs: '{{ use_ebs | default("yes") }}'

    # Use URL to download NCCL?
    use_http: '{{ use_url | default("no") }}'

    # Use s3 bucket to download NCCL?
    use_s3: '{{ use_aws | default("no") }}'
    
    # AWS s3 params. All are REQUIRED when using s3.
    s3_access_key: '{{ aws_access_key | default("null") }}'
    s3_secret_access_key: '{{ aws_secret_access_key | default("null") }}'
    s3_region: '{{ aws_region | default ("us-east-1") }}'
    s3_profile: '{{ aws_profile | default("null") }}'
    s3_bucket: '{{ bucket | default("null") }}'
    delete_aws_credentials: '{{ delete_aws_credentials_after_installation | default("no") }}'

  roles:

    # Check for NVIDIA (CUDA-capable) GPU
    - role: check_gpu
      when: gpu_check == 'yes'

    # Install NCCL from URL
    - role: install_nccl_from_url
      when: use_s3 == 'no' and use_http == 'yes' and use_ebs == 'no'

    # Install NCCL from s3 bucket
    - role: install_nccl_from_s3
      when: use_s3 == 'yes' and use_http == 'no' and use_ebs == 'no'

    # Install NCCL from EBS
    - role: install_nccl_from_ebs
      when: use_s3 == 'no' and use_http == 'no' and use_ebs == 'yes'
