---

- hosts: localhost
  connection: local
  become: yes

  vars:

    # This is the path to the CUDA installation you want to use
    CUDA_INSTALLATION: '{{ cuda_installation | default("/usr/local/cuda")'

    # This is the URL where Ansible will download the NCCL OS agnostic local installer
    NCCL_AGNOSTIC_LOCAL_INSTALLER: '{{ nccl_installer | default("") }}'

    # This is where we will install NCCL to
    NCCL_INSTALL_PATH: '{{ nccl_install_path | default("/home/nccl") }}'

  roles:

    # Check for NVIDIA (CUDA-capable) GPU
    - role: check_gpu

    # Install NCCL
    - role: install_nccl
