---

- hosts: localhost
  connection: local
  become: yes

  vars:

    # This is the path to the CUDA installation you want to use
    cuda_path: '{{ cuda_install_path | default("/usr/local/cuda")'

    # This is the URL where Ansible will download the NCCL OS agnostic local installer
    nccl_agnostic_local_installer: '{{ nccl_installer | default("") }}'

    # This is where we will install NCCL to
    nccl_agnostic_install_path: '{{ nccl_install_path | default("/home/nccl") }}'

    # Set RHEL version
    rhel_version: '{{ rhel_ver | default("7") }}'

  roles:

    # Check for NVIDIA (CUDA-capable) GPU
    - role: check_gpu

    # Install NCCL
    - role: install_nccl
