apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to run a TensorFlow build job with CPU Manager"
    tags: "tensorflow-nfd-build-job-gpu"
  name: "tensorflow-nfd-build-job-gpu"
objects:
- apiVersion: "batch/v1"
  kind: "Job"
  metadata:
    name: "${APP_NAME}"
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    template:
      metadata:
        name: "${APP_NAME}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: "${REGISTRY}/${NAMESPACE}/${IMAGESTREAM_NAME}:latest"
          command: ["/usr/libexec/s2i/run"]
          args: ["${RHEL_VERSION}", "gpu", "${NUM_GPUS}", "${CC}", "${WHICH_SOURCE}", "${NCCL_URL}", "${CUDNN_URL}", "${AWS_PROFILE}", "${AWS_REGION}", "${AWS_ACCESS_KEY}", "${AWS_SECRET_ACCESS_KEY}"]
        restartPolicy: "Never"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "beta.kubernetes.io/instance-type"
                  operator: "In"
                  values:
                  - "${INSTANCE_TYPE}"
parameters:
- description: "ImageStream name"
  name: "IMAGESTREAM_NAME"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-rhel7"
  required: true 
- description: "TensorFlow CPU Manager app name"
  name: "APP_NAME"
  from: '[A-Z0-9]{20}'
  value: "tensorflow-s2i-benchmark-app-cpu-manager"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "Current project (i.e., namespace)"
  name: "NAMESPACE"
  from: '[A-Z0-9]{15}'
  value: "openshift-image-registry"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
  required: true
- description: "RHEL version to use"
  name: "RHEL_VERSION"
  from: '[0-9]{1}'
  value: "8"
  required: true
- description: "Number of GPUs to use (must be an integer)"
  name: "NUM_GPUS"
  from: '[0-9]{5}'
  value: ""
  required: false
- description: "Which source? s3 bucket or url"
  name: "WHICH_SOURCE"
  value: "url"
  required: true
- description: "URL or s3 bucket to download NCCL from"
  name: "NCCL_URL"
  required: false
  value: ""
- description: "URL or s3 bucket to download cuDNN from"
  name: "CUDNN_URL"
  required: false
  value: ""
- description: "Path to gcc"
  name: "CC"
  value: "/usr/bin/gcc"
  required: true
- description: "AWS profile name"
  name: "AWS_PROFILE"
  required: false
- description: "AWS access key"
  name: "AWS_ACCESS_KEY"
  required: false
- description: "AWS secret access key"
  name: "AWS_SECRET_ACCESS_KEY"
  required: false
- description: "AWS region"
  name: "AWS_REGION"
  required: false
