FROM image-registry.openshift-image-registry.svc:5000/openshift-image-registry/cuda:rhel7-complete
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>
ENV LANG=en_US.utf8
USER root
ENV BUILDER_VERSION 1.0

# RHEL version (for building FFTW)
ENV RHEL_VERSION=7

# Python version
ENV PYTHON_VERSION=3.6.9

# Python path
ENV PYTHONPATH=/usr/local/lib/python3.6

# Ansible version
ENV ANSIBLE_VERSION=v2.8.6

# Set up labels
LABEL io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"
LABEL io.openshift.expose-services="8080:http"

# Put on port 8080
EXPOSE 8080

# Set timeout for yum (in seconds) to prevent Curl timeout errors w/ yum
ENV YUM_TIMEOUT=300
RUN sed -i "/[main]/a timeout=${YUM_TIMEOUT}" /etc/yum.conf

# Set top directory
ENV TOPDIR=${HOME}

# Set playbook and scripts paths
ENV TENSORFLOW_BENCHMARKS=${TOPDIR}/playbooks/TensorFlow_Models
ENV SCRIPTS_FOLDER=${TOPDIR}/scripts

# Create folders for playbooks and folder for playbooks cache
RUN mkdir -p ${TENSORFLOW_BENCHMARKS} && \
    mkdir -p ${SCRIPTS_FOLDER} && \
    mkdir -p ${TOPDIR}/.cache

# Copy playbooks and scripts
COPY TensorFlow/playbooks/TensorFlow_Models ${TENSORFLOW_BENCHMARKS}
COPY helper_scripts/Python/install_python_from_source.sh ${SCRIPTS_FOLDER}

# Put on port 8080
EXPOSE 8080

# Install Python version ${PYTHON_VERSION}
RUN cd ${SCRIPTS_FOLDER} && \
    sh install_python_from_source.sh ${PYTHON_VERSION}

# Install Ansible
RUN yum -y install git && \
    cd /tmp && \
    git clone https://github.com/ansible/ansible.git && \
    cd ansible && \
    git checkout tags/${ANSIBLE_VERSION} && \
    pip3 install -r requirements.txt && \
    pip3 install packaging && \
    sed -i "s/PYTHON=python/PYTHON=python3/g" Makefile && \
    make && \
    make install && \
    cd .. && \
    rm -rf ansible

# Create and give user permissions to modify certain directories that are required to run the Ansible
# playbooks that are being pulled into this Dockerfile. Also allow /usr/local/cuda to be writable and
# allow /.aws to be writeable in case the user wants to use an AWS s3 bucket to download NCCL + cuDNN
RUN chmod 777 /usr/libexec/s2i/run && \
    chmod g=u /etc/passwd /etc/group && \
    mkdir -p ${TOPDIR}/.ansible/tmp && \
    chmod -R 777 ${TOPDIR}/.ansible && \
    mkdir -p ${TOPDIR}/.cache && \
    chmod -R 777 ${TOPDIR}/.cache && \
    chmod 777 ${TOPDIR} && \
    touch ${TOPDIR}/.gitconfig && \
    chmod 777 ${TOPDIR}/.gitconfig && \
    mkdir ${TOPDIR}/.aws && \
    mkdir -p ${TOPDIR}/.cache/bazel && \
    chmod -R 777 ${TOPDIR}/.cache/bazel && \
    chmod -R 777 ${TOPDIR}/.aws && \
    chmod -R 777 /usr/local/cuda

# Install TensorFlow GPU
RUN pip3 install tensorflow-gpu==2.0.0b1

# Set Ansible remote tmp
RUN echo "remote_tmp = ${TOPDIR}/.ansible/tmp" >> ${TENSORFLOW_BENCHMARKS}/ansible.cfg

# Set deviceQuery path
ENV DEMO_SUITE=/usr/local/cuda/extras/demo_suite
RUN if [[ ! -f ${DEMO_SUITE} ]]; then mkdir -p ${DEMO_SUITE}; fi && \
    ln -s /usr/local/cuda/samples/1_Utilities/deviceQuery ${DEMO_SUITE}/deviceQuery

# Set user to 'default'
USER default
