---

- hosts: localhost
  connection: local

  # Set global vars
  vars:

    # FFTW build directory
    build_directory: '{{ build_dir | default("${HOME}/build") }}'

    # FFTW install directory
    install_directory: '{{ install_dir | default("${HOME}/custom_fftw") }}'

    # RHEL version
    rhel_ver: '{{ rhel_version | default("7") }}'

    # GCC path
    gcc: '{{ cc | default("/usr/bin/gcc") }}'

    # Version of FFTW3
    fftw3_ver: '{{ fftw3_version | default("3.3.8") }}'

    # Use s2i or ubi?
    ubi: '{{ use_ubi | default("no") }}'
    s2i: '{{ use_s2i | default("no") }}'

  roles:
    # Creates necessary directories for building and installing FFTW
    - role: setup

    # Gets fftw.spec and FFTW sources
    - role: get

    # Builds FFTW
    - role: build

    # Installs FFTW
    - role: install
