apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    description: "Template to make a TensorFlow build image with an FFTW NumPy backend using RHEL 7"
    tags: "tensorflow-fftw-s2i-build-gpu-ubi-aws"
  name: "tensorflow-fftw-s2i-build-gpu-ubi-aws"
objects:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "tensorflow-fftw-s2i-build-gpu-ubi-aws" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "ImageChange"
    strategy: 
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "${SOURCE_IMAGESTREAM}:latest"
        scripts: "image:///usr/libexec/s2i"
        env:
          - name: "RHEL_VERSION"
            value: "${RHEL_VERSION}"
          - name: "BACKEND"
            value: "fftw"
          - name: "DEVICE"
            value: "gpu"
          - name: "NUM_DEVICES"
            value: "${NUM_GPUS}"
          - name: "CC"
            value: "${CC}"
          - name: "WHICH_SOURCE"
            value: "${WHICH_SOURCE}"
          - name: "PYTHON_EXECUTABLE"
            value: "${PYTHON_EXECUTABLE}"
          - name: "NCCL"
            value: "${NCCL}"
          - name: "CUDNN"
            value: "${CUDNN}"
          - name: "TENSORRT"
            value: "${TENSORRT}"
          - name: "AWS_PROFILE"
            valueFrom:
              secretKeyRef:
                name: "aws-config"
                key: "profile"
          - name: "AWS_REGION"
            valueFrom:
              secretKeyRef:
                name: "aws-config"
                key: "region"
          - name: "AWS_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                name: "aws-credentials"
                key: "access_key"
          - name: "AWS_SECRET_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                name: "aws-credentials"
                key: "secret_access_key"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "${OUTPUT_IMAGESTREAM}:latest"
    nodeSelector:
      beta.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "${OUTPUT_IMAGESTREAM}"
    namespace: "openshift-image-registry"
  spec:
    dockerImageRepository: "${REGISTRY}/openshift-image-registry"
parameters:
- description: "Source ImageStream name"
  name: "SOURCE_IMAGESTREAM"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-fftw-rhel7"
  required: true
- description: "Output ImageStream name"
  name: "OUTPUT_IMAGESTREAM"
  from: '[A-Z0-9]{10}'
  value: "tensorflow-s2i-build-rhel7-gpu"
  required: true
- description: "Registry route. Use `oc registry info` to get the route after exposing it."
  name: "REGISTRY"
  value: "image-registry.openshift-image-registry.svc:5000"
  required: true
- description: "AWS instance type"
  name: "INSTANCE_TYPE"
  value: "m4.4xlarge"
- description: "RHEL version to use"
  name: "RHEL_VERSION"
  from: '[0-9]{1}'
  value: "8"
  required: true
- description: "Number of GPUs to use (must be an integer)"
  name: "NUM_GPUS"
  from: '[0-9]{5}'
  value: ""
  required: false
- description: "Path to Python executable"
  name: "PYTHON_EXECUTABLE"
  value: "/usr/bin/python3"
  required: true
- description: "Path to gcc"
  name: "CC"
  value: "/usr/bin/gcc"
  required: true
- description: "s3 bucket or url to TensorRT"
  name: "TENSORRT"
  required: false
- description: "s3 bucket or url to NCCL"
  name: "NCCL"
  required: false
- description: "s3 bucket or url to cuDNN"
  name: "CUDNN"
  required: false
- description: "Which source for NCCL, cuDNN and/or TensorRT?"
  name: "WHICH_SOURCE"
  required: true
  value: "s3"
  from: '[A-Z]{4}'
